export default [
  'https://www.amazon.com',
  'https://www.etsy.com',
  'http://www.target.com',
  'http://www.sephora.com',
  'http://www.urbanoutfitters.com',
  'http://shop.nordstrom.com',
  'http://www.ulta.com',
  'http://www.forever21.com',
  'http://www1.macys.com',
  'http://m.sephora.com',
  'https://www.victoriassecret.com',
  'https://www.chapters.indigo.ca',
  'http://www.bathandbodyworks.com',
  'https://colourpop.com',
  'http://www.worldmarket.com',
  'http://www.uncommongoods.com',
  'http://www.crateandbarrel.com',
  'http://www.williams-sonoma.com',
  'http://www.papersource.com',
  'https://www.anthropologie.com',
  'https://www.google.com',
  'https://www.francescas.com',
  'http://www.kohls.com',
  'http://www.thinkgeek.com',
  'http://www.zara.com',
  'http://www.ebay.com',
  'http://store.nike.com',
  'https://www.bedbathandbeyond.com',
  'http://www.toysrus.com',
  'http://www.westelm.com',
  'http://oldnavy.gap.com',
  'http://www.lushusa.com',
  'http://www.dickssportinggoods.com',
  'http://www.anthropologie.com',
  'http://www.notonthehighstreet.com',
  'http://www.toysrus.ca',
  'https://shop.lululemon.com',
  'https://www.walmart.com',
  'http://www.modcloth.com',
  'http://www.thebay.com',
  'http://www.hm.com',
  'http://www.potterybarn.com',
  'http://www.walmart.ca',
  'https://www.disneystore.com',
  'http://www.zappos.com',
  'http://www.gap.com',
  'http://www.hottopic.com',
  'http://www.landofnod.com',
  'http://www.bestbuy.com',
  'https://www.starbucks.com',
  'https://www.morphebrushes.com',
  'http://www.nflshop.com',
  'https://www.kyliecosmetics.com',
  'https://www.target.com.au',
  'http://m.shop.nordstrom.com',
  'https://www.jcrew.com',
  'http://www.maccosmetics.com',
  'https://m.indigo.ca',
  'http://www.vans.com',
  'http://m.nike.com',
  'http://www.ikea.com',
  'http://www1.bloomingdales.com',
  'http://www.asos.com',
  'http://www.pier1.com',
  'http://www.elfcosmetics.com',
  'http://www.apple.com',
  'http://www.lush.ca',
  'http://www.bookdepository.com',
  'https://society6.com',
  'https://amzn.com',
  'http://www.bestbuy.ca',
  'https://www.underarmour.com',
  'http://www.carters.com',
  'https://www.instagram.com',
  'http://www.potterybarnkids.com',
  'https://www.rei.com',
  'http://www.aritzia.com',
  'http://www.saje.com',
  'http://www2.hm.com',
  'http://tjmaxx.tjx.com',
  'http://www.loft.com',
  'http://www.hobbylobby.com',
  'http://m.pandora.net',
  'https://www.uniqlo.com',
  'http://www.selfridges.com',
  'https://www.freepeople.com',
  'http://www.containerstore.com',
  'https://www.davidstea.com',
  'http://www.homedepot.com',
  'https://www.origamiowl.com',
  'http://www.toms.com',
  'https://www.thenorthface.com',
  'http://www.aldoshoes.com',
  'http://www.zumiez.com',
  'http://www.lazada.com.ph',
  'http://www.ebay.co.uk',
  'http://www.alexandani.com',
  'https://www.sportchek.ca',
  'http://www.cb2.com',
  'http://www.markandgraham.com',
  'https://www.luluandgeorgia.com',
  'http://www.dsw.com',
  'https://www.madewell.com',
  'http://shop.davidjones.com.au',
  'http://m.macys.com',
  'http://www.academy.com',
  'http://www.boots.com',
  'http://www.simons.ca',
  'http://www.americangirl.com',
  'https://merchant.sgiftcard.com',
  'https://www.tillys.com',
  'https://m.bedbathandbeyond.com',
  'http://www.michaels.com',
  'http://www.llbean.com',
  'http://nintendowire.com',
  'http://m.toysrus.com',
  'https://www.turtlefeathers.net',
  'http://m.toysrus.ca',
  'https://incentive.giftcertificates.com',
  'http://www.pacsun.com',
  'http://www.marksandspencer.com',
  'https://www.katespade.com',
  'http://toyhax.com',
  'http://m.bathandbodyworks.com',
  'http://www.fanatics.com',
  'http://m.costco.com',
  'https://www.nordstromrack.com',
  'http://www.barnesandnoble.com',
  'http://www.adidas.com',
  'https://www.popcultcha.com.au',
  'http://www.surlatable.com',
  'http://www.dynamiteclothing.com',
  'http://www.chapters.indigo.ca',
  'https://www.homedepot.ca',
  'https://www.google.ca',
  'http://store.nba.com',
  'http://www.charlotterusse.com',
  'http://www.kmart.com.au',
  'http://www.thebodyshop.ca',
  'http://m.dickssportinggoods.com',
  'http://www.express.com',
  'http://www.dunkindonuts.com',
  'http://www.thegiftcardcentre.co.uk',
  'http://www.bhcosmetics.com',
  'http://www.zulily.com',
  'http://www.yesstyle.com',
  'http://m2.hm.com',
  'http://www.roots.com',
  'http://www.redbubble.com',
  'https://www.gadventures.com',
  'https://m.disneystore.com',
  'http://www.jcpenney.com',
  'https://houseoflashes.com',
  'http://www.callitspring.com'
]
/*

  { count: 116, name: 'http://www.uncommongoods.com' },
  { count: 112, name: 'http://www.crateandbarrel.com' },
  { count: 112, name: 'http://www.williams-sonoma.com' },
  { count: 112, name: 'http://www.papersource.com' },
  { count: 104, name: 'https://www.anthropologie.com' },
  { count: 102, name: 'https://www.google.com' },
  { count: 101, name: 'https://www.francescas.com' },
  { count: 95, name: 'http://www.kohls.com' },
  { count: 89, name: 'http://www.thinkgeek.com' },
  { count: 87, name: 'http://www.zara.com' },
  { count: 86, name: 'http://www.ebay.com' },
  { count: 82, name: 'http://store.nike.com' },
  { count: 77, name: 'https://www.bedbathandbeyond.com' },
  { count: 76, name: 'http://www.toysrus.com' },
  { count: 75, name: 'http://www.westelm.com' },
  { count: 74, name: 'http://oldnavy.gap.com' },
  { count: 71, name: 'http://www.lushusa.com' },
  { count: 68, name: 'http://www.dickssportinggoods.com' },
  { count: 68, name: 'http://www.anthropologie.com' },
  { count: 67, name: 'http://www.notonthehighstreet.com' },
  { count: 66, name: 'http://www.toysrus.ca' },
  { count: 65, name: 'https://shop.lululemon.com' },
  { count: 65, name: 'https://www.walmart.com' },
  { count: 64, name: 'http://www.modcloth.com' },
  { count: 63, name: 'http://www.thebay.com' },
  { count: 62, name: 'http://www.hm.com' },
  { count: 61, name: 'http://www.potterybarn.com' },
  { count: 61, name: 'http://www.walmart.ca' },
  { count: 58, name: 'https://www.disneystore.com' },
  { count: 56, name: 'http://www.zappos.com' },
  { count: 53, name: 'http://www.gap.com' },
  { count: 52, name: 'http://www.hottopic.com' },
  { count: 52, name: 'http://www.landofnod.com' },
  { count: 50, name: 'http://www.bestbuy.com' },
  { count: 49, name: 'https://www.starbucks.com' },
  { count: 48, name: 'https://www.morphebrushes.com' },
  { count: 47, name: 'http://www.nflshop.com' },
  { count: 44, name: 'https://www.kyliecosmetics.com' },
  { count: 43, name: 'https://www.target.com.au' },
  { count: 43, name: 'http://m.shop.nordstrom.com' },
  { count: 42, name: 'https://www.jcrew.com' },
  { count: 41, name: 'http://www.maccosmetics.com' },
  { count: 40, name: 'https://m.indigo.ca' },
  { count: 40, name: 'http://www.vans.com' },
  { count: 39, name: 'http://m.nike.com' },
  { count: 38, name: 'http://www.ikea.com' },
  { count: 37, name: 'http://www1.bloomingdales.com' },
  { count: 37, name: 'http://www.asos.com' },
  { count: 34, name: 'http://www.pier1.com' },
  { count: 33, name: 'http://www.elfcosmetics.com' },
  { count: 33, name: 'http://www.apple.com' },
  { count: 32, name: 'http://www.lush.ca' },
  { count: 32, name: 'http://www.bookdepository.com' },
  { count: 32, name: 'https://society6.com' },
  { count: 32, name: 'https://amzn.com' },
  { count: 31, name: 'http://www.bestbuy.ca' },
  { count: 30, name: 'https://www.underarmour.com' },
  { count: 30, name: 'http://www.carters.com' },
  { count: 30, name: 'https://www.instagram.com' },
  { count: 30, name: 'http://www.potterybarnkids.com' },
  { count: 29, name: 'https://www.rei.com' },
  { count: 29, name: 'http://www.aritzia.com' },
  { count: 29, name: 'http://www.saje.com' },
  { count: 29, name: 'http://www2.hm.com' },
  { count: 28, name: 'http://tjmaxx.tjx.com' },
  { count: 28, name: 'http://www.loft.com' },
  { count: 28, name: 'http://www.hobbylobby.com' },
  { count: 28, name: 'http://m.pandora.net' },
  { count: 27, name: 'https://www.uniqlo.com' },
  { count: 27, name: 'http://www.selfridges.com' },
  { count: 27, name: 'https://www.freepeople.com' },
  { count: 26, name: 'http://www.containerstore.com' },
  { count: 26, name: 'https://www.davidstea.com' },
  { count: 26, name: 'http://www.homedepot.com' },
  { count: 25, name: 'https://www.origamiowl.com' },
  { count: 25, name: 'http://www.toms.com' },
  { count: 24, name: 'https://www.thenorthface.com' },
  { count: 24, name: 'http://www.aldoshoes.com' },
  { count: 24, name: 'http://www.zumiez.com' },
  { count: 24, name: 'http://www.lazada.com.ph' },
  { count: 24, name: 'http://www.ebay.co.uk' },
  { count: 24, name: 'http://www.alexandani.com' },
  { count: 23, name: 'https://www.sportchek.ca' },
  { count: 23, name: 'http://www.cb2.com' },
  { count: 22, name: 'http://www.markandgraham.com' },
  { count: 21, name: 'http://www.dsw.com' },
  { count: 21, name: 'https://www.madewell.com' },
  { count: 21, name: 'http://shop.davidjones.com.au' },
  { count: 20, name: 'http://m.macys.com' },
  { count: 20, name: 'http://www.academy.com' },
  { count: 20, name: 'http://www.boots.com' },
  { count: 20, name: 'http://www.simons.ca' },
  { count: 20, name: 'http://www.americangirl.com' },
  { count: 20, name: 'https://merchant.sgiftcard.com' },
  { count: 20, name: 'https://www.tillys.com' },
  { count: 20, name: 'https://m.bedbathandbeyond.com' },
  { count: 20, name: 'http://www.michaels.com' },
  { count: 19, name: 'http://www.llbean.com' },
  { count: 19, name: 'http://nintendowire.com' },
  { count: 19, name: 'http://m.toysrus.com' },
  { count: 19, name: 'https://www.turtlefeathers.net' },
  { count: 19, name: 'http://m.toysrus.ca' },
  { count: 19, name: 'https://incentive.giftcertificates.com' },
  { count: 19, name: 'http://www.pacsun.com' },
  { count: 19, name: 'http://www.marksandspencer.com' },
  { count: 18, name: 'https://www.katespade.com' },
  { count: 18, name: 'http://toyhax.com' },
  { count: 18, name: 'http://m.bathandbodyworks.com' },
  { count: 18, name: 'http://www.fanatics.com' },
  { count: 17, name: 'http://m.costco.com' },
  { count: 17, name: 'https://www.nordstromrack.com' },
  { count: 17, name: 'http://www.barnesandnoble.com' },
  { count: 16, name: 'http://www.adidas.com' },
  { count: 16, name: 'https://www.popcultcha.com.au' },
  { count: 16, name: 'http://www.surlatable.com' },
  { count: 16, name: 'http://www.dynamiteclothing.com' },
  { count: 16, name: 'http://www.chapters.indigo.ca' },
  { count: 16, name: 'https://www.homedepot.ca' },
  { count: 16, name: 'https://www.google.ca' },
  { count: 16, name: 'http://store.nba.com' },
  { count: 15, name: 'http://www.charlotterusse.com' },
  { count: 15, name: 'http://www.kmart.com.au' },
  { count: 15, name: 'http://www.thebodyshop.ca' },
  { count: 15, name: 'http://m.dickssportinggoods.com' },
  { count: 15, name: 'http://www.express.com' },
  { count: 15, name: 'http://www.dunkindonuts.com' },
  { count: 15, name: 'http://www.thegiftcardcentre.co.uk' },
  { count: 15, name: 'http://www.bhcosmetics.com' },
  { count: 14, name: 'http://www.zulily.com' },
  { count: 14, name: 'http://www.yesstyle.com' },
  { count: 14, name: 'http://m2.hm.com' },
  { count: 14, name: 'http://www.roots.com' },
  { count: 14, name: 'http://www.redbubble.com' },
  { count: 14, name: 'https://www.gadventures.com' },
  { count: 14, name: 'https://m.disneystore.com' },
  { count: 14, name: 'http://www.jcpenney.com' },
  { count: 14, name: 'https://houseoflashes.com' },
  { count: 13, name: 'http://www.callitspring.com' } ]*/


