
export const REQUEST_URL_STARTING = 'REQUEST_URL_STARTING'
export const REQUEST_URL_FAILED = 'REQUEST_URL_FAILED'
export const REQUEST_URL_RECEIVED = 'REQUEST_URL_RECEIVED'
export const REQUEST_IMAGES_STARTING = 'REQUEST_IMAGES_STARTING'
export const REQUEST_IMAGES_RECEIVED = 'REQUEST_IMAGES_RECEIVED'
